export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const SET_FILES = 'SET_FILES';
export const SET_CURRENT_DIR = 'SET_CURRENT_DIR';
export const ADD_FILE = 'ADD_FILE';
export const SET_POPUP_DISPLAY = 'SET_POPUP_DISPLAY';
export const PUSH_TO_STACK = 'PUSH_TO_STACK';
export const DELETE_FILE = 'DELETE_FILE';
export const SHOW_UPLOADER = 'SHOW_UPLOADER';
export const HIDE_UPLOADER = 'HIDE_UPLOADER';
export const ADD_UPLOAD_FILE = 'ADD_UPLOAD_FILE';
export const REMOVE_UPLOAD_FILE = 'REMOVE_UPLOAD_FILE';
export const CHANGE_UPLOAD_FILE = 'CHANGE_UPLOAD_FILE';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const createUser = user => ({type: SET_USER, payload: user});
export const logout = () => ({type: LOGOUT});
export const createFiles = files => ({type: SET_FILES, payload: files});
export const setCurrentDir = currentDir => ({type: SET_CURRENT_DIR, payload: currentDir});
export const addFile = file => ({type: ADD_FILE, payload: file});
export const setPopupDisplay = popup => ({type: SET_POPUP_DISPLAY, payload: popup});
export const pushToStack = stack => ({type: PUSH_TO_STACK, payload: stack});
export const deleteFileAction = file => ({type: DELETE_FILE, payload: file});
export const showUploader = () => ({type: SHOW_UPLOADER});
export const hideUploader = () => ({type: HIDE_UPLOADER});
export const addUploadFile = file => ({type: ADD_UPLOAD_FILE, payload: file});
export const removeUploadFile = fileId => ({type: REMOVE_UPLOAD_FILE, payload: fileId});
export const changeUploaderFile = file => ({type: CHANGE_UPLOAD_FILE, payload: file});
export const showLoader = () => ({type: SHOW_LOADER});
export const hideLoader = () => ({type: HIDE_LOADER});
